### ISSUE TITLE
[docs] administrator diagram 그림 그려서 추가하기 

### ISSUE THREAD

**Issue by minseungseon** [cau-swe/checkpoint-1#19]
## Task

- [ ] administrator diagram 그림 그려서 추가하기 
- [ ] 상민씨에게 중간중간 잘 하고 있는지 확인하면서 작업해보기 
- [ ] 수요일 점심까지 해서 PR 날려놓기~ 

## reference - By @Topslug 
- page maker Use Case, 및 공란 확인하는 UseCase (입력을 했을 때 비어있는지 확인하기) Diagram DRAFT
![image](https://user-images.githubusercontent.com/37579661/114412478-19a69e80-9be8-11eb-9837-80fc820d6876.png)
![image](https://user-images.githubusercontent.com/37579661/114412662-4490f280-9be8-11eb-89c8-f0bd2b205b93.png)

- 해당 Use Case 최종 DRAFT
![image](https://user-images.githubusercontent.com/37579661/114413222-c254fe00-9be8-11eb-9249-b908f7315ddf.png)

**Comment by minseungseon** [comment]
해결!
