### ISSUE TITLE
[docs] Administrator - Use Case, Domain Model 다이어그램 구성해오기 

### ISSUE THREAD

**Issue by minseungseon** [cau-swe/checkpoint-1#5]
## Task
- [ ] Use Case 별로 스키마 적어오기
- [ ] Diagram 이미지파일로 첨부
- [ ] Use Case Model with Traceability Matrix
- [ ]  Domain model(E-C-B) with Traceability Matrix 
- [ ] requirement와 Use Case 와의 상관관계에 대해 구체적으로 조사해오기
- [ ] User Interface mockups
