### ISSUE TITLE
[docs] Customer - Use Case, Domain Model 다이어그램 구성해오기 

### ISSUE THREAD

**Issue by minseungseon** [cau-swe/checkpoint-1#6]
## Task
- [x] Use Case 별로 스키마 적어오기
- [x] Diagram 이미지파일로 첨부
- [x] Use Case Model with Traceability Matrix 
- [ ] Domain model(E-C-B) with Traceability Matrix 
- [ ] requirement와 Use Case 와의 상관관계에 대해 구체적으로 조사해오기
- [ ] User Interface mockups
